### ISSUE TITLE
[MVP] Roadmap

### ISSUE THREAD

**Issue by gkueny** [Gatsbylius/gatsbylius-starter#1]
To have a viable Gastby starter we need: 

* [x] Improve project design: *plugin source*, *starter*
* [ ] Improve doc, guidelines
* [ ] Add a 404 page
* [ ] Provide a solution for CMS pages
* [ ] Find a way to handle payments
* [ ] Catalog: 
* * [ ] Simple product, 
* * [ ] simple variantes product
* * [ ] Category page
* [ ] Cart 
* [ ] Checkout
* [ ] Basic SEO : `<SEO/>` component, sitemap, robots, microdata, redirections
* [ ] Accessibility
* [ ] CI
* [ ] Tests

**Comment by adrien-louis-r** [comment]
Thanks for that !

Some feedback :

> Improve doc, guidelines

Alongside the guidelines, we have to describe our choices concerning certain technical aspect of the project, like how to handle styles or coding choice, tooling (prettier, etc...) and testing. It will help guide people who want to contribute how to do so.

> Provide a solution for CMS pages

Sylius does not provide a native CMS solution for now. So I think we can pospone this point. In the MVP, Gatsby may be enough by itself for that.

> Tests

As for now and the current state of the projet, once we migrate to a stater, this point should have our priority. It will vastly help us to add features to the project. For now we have a small POC / MVP. If we want it to be production ready, this is an important point.
IMO testing critical paths with Cypress is a priority. What do you think about that?

**Comment by gkueny** [comment]
Thanks you for your feedbacks.
I agree we have to "describe our choices concerning certain technical aspect of the project, like how to handle styles or coding choice, tooling (prettier, etc...) ". 

You right on CMS. I think we can postpone too.


> IMO testing critical paths with Cypress is a priority. What do you think about that?
I totally agree, testing is critical and this help us to create new feature confidently

**Comment by imhaage** [comment]
Thank you, great job!

I agree with you both.

> Sylius does not provide a native CMS solution for now
Sylius doen't have a native CMS solution but there is an "approved by sylius" plugin much appreciated by the community: https://sylius.com/plugin/cmsplugin/
Maybe there is something to do with it.

> Improve doc, guidelines
What kind of tool you'd choose for the doc ?
- gatsby ?
- docusauraus ?
- GitBook ? there is a mention on their website about open-source projects they'll be gald to help, maybe it's worth to contact them

> we have to describe our choices concerning certain technical aspect of the project
As the project started really fast we had to make some choices really quickly. But as the projecthas just started some technical choices should be discussed before it's too late to go back. 
For example I know styled-components are not a totally popular solution for styling. So maybe going back to SASS could allow people to be onboarded on the project more easily. It could be a starting point to the description of our choices.

Once have discussed our technical choices (like styled-components I'll be glad to continue the product page, go back to where I left off:
> Simple product,
> Simple variantes product

**Comment by gkueny** [comment]
> Sylius doesn't have a native CMS solution but there is an "approved by sylius" plugin much appreciated by the community: https://sylius.com/plugin/cmsplugin/
Maybe there is something to do with it.

Yeah we can do something with it, but as @adrien-louis-r said, I think we can postpone that.

> What kind of tool you'd choose for the doc ?

Maybe for now just our README.md, CONTRIBUTE.md, ...


> Once we have discussed our technical choices (like styled-components) I'll be glad to continue the product page, go back to where I left off:

I attribute it to you. 
But like you said, let talk about our technical choice first. 
Maybe an another issue to discuss it, is a good idea : https://github.com/Gatsbylius/gatsbylius-starter/issues/3

**Comment by gkueny** [comment]
As discussed here https://github.com/Gatsbylius/Gatsbylius/issues/49

[React version of StorefrontUI](https://github.com/DivanteLtd/storefront-ui/tree/react-setup) can be a good idea for our UI.

**Comment by gkueny** [comment]
> For example I know styled-components are not a totally popular solution for styling. So maybe going back to SASS could allow people to be onboarded on the project more easily.

As a personal note, I prefer use plain old school css or `sass`. It's more beginner's friendly I think
